# Generated by Django 3.1 on 2020-10-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='massage',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
