# Generated by Django 3.1 on 2020-10-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udi', '0002_auto_20201007_0514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='massage',
        ),
    ]
