# Generated by Django 3.1 on 2020-10-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udi', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
